version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80" 
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    networks:
      - app-network
    volumes:
      - backend-data:/app/data

networks:
  app-network:
    driver: bridge

volumes:
  backend-data:
